name: Create PR on Push to Feature Branch

on:
  push:
    branches:
      - feature

jobs:
  create_pr:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Install hub
      run: |
        sudo apt-get update -q
        sudo apt-get install -yq jq
        curl -fsSL https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz -o hub.tgz
        tar -zxf hub.tgz
        sudo ./hub-linux-amd64-2.14.2/install
        rm -rf hub.tgz hub-linux-amd64-2.14.2
      shell: bash

    - name: Create PR
      env:
        GITHUB_TOKEN: ${{ secrets.CI_CD }}
      run: |
        hub pr create -b main -h $GITHUB_REPOSITORY -t "Automated PR from feature branch" -m "This PR was automatically created from a feature branch."
